name: pptrans
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - tk
  - tcl
  - pip:
    - python-pptx==0.6.23
    - googletrans==4.0.0rc1
    - requests==2.31.0
    - pyinstaller==6.3.0
    - pytest==7.4.4
    - pytest-cov==4.1.0